# Generated by Django 5.1.4 on 2024-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('category', models.IntegerField(choices=[(1, 'shoes'), (2, 'mobile'), (3, 'cloths'), (4, 'watch')], verbose_name='Product Name')),
                ('description', models.CharField(max_length=300, verbose_name='Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Available')),
                ('image', models.ImageField(upload_to='image')),
                ('offer_price', models.IntegerField(default=0)),
            ],
        ),
    ]
