# Generated by Django 5.1.4 on 2025-01-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
