# Generated by Django 5.1.4 on 2025-01-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
